### ISSUE TITLE
Property List Order

### ISSUE THREAD

**Issue by VeriumETH** [nftchef/art-engine-viewer#2]
Hello @nftchef 

First of all, thank you for all of your hard work!

Is there any way for the list of individual property names be ordered alphabetically? For example the photo shown has 'Eyes' properties listed in a non-consecutive order. round, Sarcastic, Eyes-chibi, Nouns Glasses. I want the order to be shown as Eyes-chibi, Nouns Glasses, round, Sarcastic. I've gone over the documentation for customizing the vue styling but I don't believe it says anything about what I'm asking. Any help from anyone would be greatly appreciated!

**Comment by nftchef** [comment]
Hi! Thank you. Are you hoping to sort the sidebar filters alphabetically? That can be done with a standard `Array.sort` function. I can add that.

**Comment by VeriumETH** [comment]
Oh jeez, I was looking into some way more complicated ways of doing this. Yes, that is exactly what I'm looking for.  If you could I would really appreciate it. 🙏

**Comment by nftchef** [comment]
Fixed in the last commit https://github.com/nftchef/art-engine-viewer/commit/9fbfb58e16e5c49603c93a738fbb91b6ad8e896b

**Comment by VeriumETH** [comment]
Bless you 🙏
